# Blueprint for East Coast e-bike warranty claims repair center
version: "1"
services:
  - type: web
    name: warranty-hub
    runtime: python
    repo:
https://github.com/mikey83mikey83-42/
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    autoDeployTrigger: commit
    
